### ISSUE TITLE
Reduced screen max brightness

### ISSUE THREAD

**Issue by kk1987** [daliansky/XiaoXinPro-13-2019-hackintosh#10]
i7，华星光电屏幕，BIOS=32WW，latest OC

屏幕最大亮度用i1Display Pro实测：
Windows 10 / Arch Linux 下为340nits，macOS下只有270nits（插电源，或者关闭"slightly dim the display"之后的电池供电）

**Comment by M69W** [comment]
没设备测试，有可能是亮度调节有限制？

**Comment by kk1987** [comment]
找到原因了，Fn+F12无法将亮度调到最大。。手动把亮度滑块拉到最右是可以达到340nits的。
