### ISSUE TITLE
v3.0.2 CPU变频问题

### ISSUE THREAD

**Issue by stoness2324** [daliansky/XiaoXinPro-13-2019-hackintosh#162]
OTA升级mac os12。全程无痛。EFI使用config-YOGASMC.plist。
CPU是10210U，测试发现全核心3.4没问题，但是单核心最高也只有3.4了，
是不是需要使用cpuifriend搞一搞变频？
希望大家都测试一下CPU变频的情况。

**Comment by M69W** [comment]
看看是不是 设置了 性能模式 ？

**Comment by stoness2324** [comment]
@M69W 安装了panel，分别在性能模式、标准、安静模式下测试，intel power gadget数据显示，单核心始终只能3.4

**Comment by M69W** [comment]
/issues/89

/issues/132

试试以上

**Comment by stoness2324** [comment]
@M69W 感谢指点。
回去我先尝试修改机型，然后增加cpufriend
