### ISSUE TITLE
电池问题

### ISSUE THREAD

**Issue by cytown** [daliansky/XiaoXinPro-13-2019-hackintosh#251]
我使用了最新的SSDT-BAT_BST-fix.aml，没有使用其它电池相关acpi，结果电池就不显示了。

如果加上之前禁用的SSDT-BATS-PRO13.aml，电池可以显示了，但是变成电池一直是0，而且不充电。。。

请教大家如何解决。

<img width="668" alt="iShot_2023-07-10_11 41 31" src="https://github.com/daliansky/XiaoXinPro-13-hackintosh/assets/148625/8a93840e-1ada-4e46-8337-c889b950cc8a">
<img width="300" alt="iShot_2023-07-10_12 10 08" src="https://github.com/daliansky/XiaoXinPro-13-hackintosh/assets/148625/7e24ed7d-67b8-452a-a775-dd0dd5480e1a">

**Comment by cytown** [comment]
我是因为之前显示电池需要维修才增加的fix这个acpi。

**Comment by hsiang6** [comment]
你们的电池序列号变成123456789了吗，在windows上 这个可以改回原本正确的SN吗，

**Comment by cytown** [comment]
> 你们的电池序列号变成123456789了吗，在windows上 这个可以改回原本正确的SN吗，

序列号怎么改？？？我没试windows，因为主要在mac上用，windows只是特殊情况才会用一下，基本不用。

 
<img width="903" alt="iShot_2023-07-10_15 36 40" src="https://github.com/daliansky/XiaoXinPro-13-hackintosh/assets/148625/0174ba7f-cef1-4d63-b9a9-2aaad84f88bd">

**Comment by cytown** [comment]
汗，是我自己的问题，删除了SSDT-OCBAT1-lenovoPRO13.aml了，以为这两个文件是一样的。

奇怪的是088以后的oc里好像这两个aml都没有，但是也不影响运行吧？我从071自己升级上来的必须要这两个文件，否则就不显示电池信息。
