### ISSUE TITLE
有没有安装Sonoma成功的

### ISSUE THREAD

**Issue by qqsir-dev** [daliansky/XiaoXinPro-13-2019-hackintosh#255]
有没有在Ventura升级到Sonoma成功的，或者安装成功的，分享一下经验，谢谢。

**Comment by feifan1113** [comment]
只能整个安装包 安装升级 而且wifi驱动 用不了，按照网上教程配合这个https://github.com/dortania/OpenCore-Legacy-Patcher   wifi依然用不了

**Comment by fanboynet** [comment]
直接升级就可以，记得更新最新版本的OC和KEXT。
另外博通的wifi全挂，苹果官方不再支持，但使用可以用回intel的wifi，目前可以驱动。
https://github.com/OpenIntelWireless/itlwm/issues/883
[AirportItlwm-Sonoma-Preview05.zip](https://github.com/OpenIntelWireless/itlwm/files/12299048/AirportItlwm-Sonoma-Preview05.zip)
一定要用BCM的话，只能用OpenCore Legacy Patcher打内核补丁。

**Comment by feifan1113** [comment]
> 直接升级就可以，记得更新最新版本的OC和KEXT。 另外博通的wifi全挂，苹果官方不再支持，但使用可以用回intel的wifi，目前可以驱动。 [OpenIntelWireless/itlwm#883](https://github.com/OpenIntelWireless/itlwm/issues/883) [AirportItlwm-Sonoma-Preview05.zip](https://github.com/OpenIntelWireless/itlwm/files/12299048/AirportItlwm-Sonoma-Preview05.zip) 一定要用BCM的话，只能用OpenCore Legacy Patcher打内核补丁。

博通的试过了，安装网上的教程打补丁，使用本项目的EFI，开机会卡进度条，一直不成功

**Comment by qqsir-dev** [comment]
多谢各位，成功安装了，我用的intelAx201已经成功驱动WI-FI

**Comment by Marvin2020-China** [comment]
楼主，能不能把SONOMA的EFI共享下？
