### ISSUE TITLE
c口外接4k显示器，经常在电脑开机后显示器没有信号

### ISSUE THREAD

**Issue by gaoxianglyx** [daliansky/XiaoXinPro-13-2019-hackintosh#258]
显示器电源接通的，然后打开电脑，可能有50%的几率显示器没有信号，
这时候重新插拔c口信号线，就有信号了，
或是把显示器电源重新关闭，打开，也能解决（有时候需要重复开关电源两次）
请教下能否解决

**Comment by M69W** [comment]
从仅有的信息来看，无法重现。

**Comment by LaymanBrian** [comment]
试试在bootargs里加上igfxonln=1

**Comment by gaoxianglyx** [comment]
> 试试在bootargs里加上igfxonln=1

谢谢，已经卖了
