### ISSUE TITLE
Sonoma下免驱卡BCM94360Z4的Wi-Fi驱动失败

### ISSUE THREAD

**Issue by AkimioJR** [daliansky/XiaoXinPro-13-2019-hackintosh#260]
我看好像是苹果官方取消了对博通网卡的Wi-Fi支持，但我又想用AirPods流转和隔空投送，Apple Watch解锁等服务，各位有没有什么好的解决方法

**Comment by M69W** [comment]
https://blog.daliansky.net/
看下小兵博客，有提及

**Comment by M69W** [comment]
> 我看好像是苹果官方取消了对博通网卡的Wi-Fi支持，但我又想用AirPods流转和隔空投送，Apple Watch解锁等服务，各位有没有什么好的解决方法

参考这里
https://github.com/5T33Z0/OC-Little-Translated/blob/main/14_OCLP_Wintel/Enable_Features/WiFi_Sonoma.md

**Comment by AkimioJR** [comment]
> > 我看好像是苹果官方取消了对博通网卡的Wi-Fi支持，但我又想用AirPods流转和隔空投送，Apple Watch解锁等服务，各位有没有什么好的解决方法
> 
> 
> 
> 参考这里
> 
> https://github.com/5T33Z0/OC-Little-Translated/blob/main/14_OCLP_Wintel/Enable_Features/WiFi_Sonoma.md
> 
> 
> 
> 
> 
> 

感谢回复
