### ISSUE TITLE
i7-10710U屏幕显示出现大量黑点问题

### ISSUE THREAD

**Issue by Akoasmn** [daliansky/XiaoXinPro-13-2019-hackintosh#262]
配置是小新pro13-2020-i710710U-西数SN750-BCM943602CS，EFI用的是小新群里宪武大佬23年9月发出的0.9.5版本。在网上查阅了很久没有遇到过类似的情况，出现的现象如下图。
<img width="506" alt="githib com" src="https://github.com/user-attachments/assets/3bc931ee-8360-4d14-b02a-c078864e4756">
<img width="360" alt="① Q ① 山，20o6" src="https://github.com/user-attachments/assets/abdb4c20-6f9c-4b78-9585-1c053dead592">
<img width="470" alt="Pasted Graphic 2" src="https://github.com/user-attachments/assets/a7a3019f-0a9b-4949-9834-5caf9a3a4fe2">
<img width="585" alt="macosMonterey" src="https://github.com/user-attachments/assets/934c2a0a-ce9a-4761-b1c3-057b4029b7f5">
最初装黑果的时候还没有这个现象，不知道哪天误改动了什么就出现了这个，重装过几次系统，换过EFI，仿冒显卡换过几对AAPL,ig-platform-id，都会有这种现象，不同的显卡ID出现此现象的严重程度不一样，调整过缓冲帧一系列显存大小，还注入了EDID，开启HIDPI也还是有这种现象。可以确定的是不仿冒显卡ID，显存7M，核显无驱动的时候不会出现这种现象，因此感觉是驱动的问题。
<img width="518" alt="Intel CoffeeLake-U GT3e firis Plus Graphics 655" src="https://github.com/user-attachments/assets/6da84bee-50db-4263-a03a-e2b406043a99">

**Comment by Jameslo1987** [comment]
老哥你这个u，核显负载会超过1.2Ghz基准频率吗，我的只要调用核显负载就会上升到4～5Ghz，抢了cpu全部的功耗cpu会降频到400～800Mhz。Intel power gadget 测试核显最大频率就可以复现这个问题。
![F0252E4AFA3E5E4F79E4D1AC96512B62](https://github.com/user-attachments/assets/fb25269b-5c2c-4505-b3de-012e1292470e)

**Comment by Akoasmn** [comment]
> 老哥你这个u，核显负载会超过1.2Ghz基准频率吗，我的只要调用核显负载就会上升到4～5Ghz，抢了cpu全部的功耗cpu会降频到400～800Mhz。Intel power gadget 测试核显最大频率就可以复现这个问题。 !

刚跑了一下，我的CPU频率比你的稍微高一点，但GFX最高也能超过5，但是我记得之前是在远景还是哪里看到过十代U测试不准的说法，不确定是不是真的有问题，以跑分为准吧。
<img width="398" alt="截屏2024-08-29 11 45 36 1" src="https://github.com/user-attachments/assets/d63a0738-926e-43d1-9e6c-4c2c75202221">
<img width="940" alt="截屏2024-08-29 11 52 55" src="https://github.com/user-attachments/assets/d700e156-d98f-4084-89ff-99458d2e1aa0">

**Comment by Jameslo1987** [comment]
感谢回复，我漏说了我是核显与全核心同时测试的，远景的我看到过但不认可这种说法，因为在win下同样看4k视频或者调用核显高负载操作，核显频率永远不会超过基准频率，系统不会卡顿，cpu也不会降频到这么低。

黑苹果里看同样的4k视频，不用上工具看频率就能感觉非常明显的卡顿，我尝试过了非常多的方法，都无法将核显频率保持在基准频率下。

10代台式反而没这样的问题，看来10代笔记本cpu都会这样，不止10u系列，H系列都这样。我翻了很多类似问题都有这种现象，但只有很少部分人提及，看来这个问题无解了虽然能用但是我确实感觉到卡顿。

苹果官方支持的，笔记本10xxGx，台式10x00，核显睿频才是正常。

对于你提出的问题我没遇到过，看到过类似但只发生在独显上是显存问题，但黑苹果都是核显显存是调用内存的。
我的思路是在win下使用一段时间，并烤机看看是否会复现。
至于黑苹果如果系统是新安装的则排除系统问题，尝试更换其他核显的AAPL,ig-platform-id 去逐个试，如果是隐性问题那就很费神了，主要定位出问题是硬件或软件。

**Comment by XyoZang** [comment]
可能是硬件问题

**Comment by Akoasmn** [comment]
打扰了，可能是硬件问题，有一段时间突然没问题了，持续了两三个小时又恢复原状，期间没有什么软件变动，应该可以排除软件问题，暂时将就用吧。

**Comment by XyoZang** [comment]
打扰了，可能是硬件问题，有一段时间突然没问题了，持续了两三个小时又恢复原状，期间没有什么软件变动，应该可以排除软件问题，暂时将就用吧。
