### ISSUE TITLE
IOConsoleUsers: time(0) 0->0, lin 0, llk 1, IOConsoleUsers: gIOScreenLockState 3, hs 0, bs 0, nov 0, sm 0x0

### ISSUE THREAD

**Issue by mxpazyj** [daliansky/XiaoXinPro-13-2019-hackintosh#3]
机型：小新Pro13-i7
取消勾选 `AAPL,ig-platform-id` 能进入系统
勾选的话卡`IOConsoleUsers: time(0) 0->0, lin 0, llk 1, IOConsoleUsers: gIOScreenLockState 3, hs 0, bs 0, nov 0, sm 0x0`
尝试过`sudo kextcache -i /`重建缓存，结果也是一样
大佬麻烦帮忙看看怎么解决

**Comment by M69W** [comment]
这里还没有更新i7版的
欢迎加入小新pro 黑苹果，群聊号码：946132482

**Comment by mxpazyj** [comment]
进Q群了，但是好像只有极少部分人遇到这种情况，在Q群反馈没人理解
好像是因为屏幕是友达屏幕的原因？

**Comment by M69W** [comment]
> 进Q群了，但是好像只有极少部分人遇到这种情况，在Q群反馈没人理解
> 好像是因为屏幕是友达屏幕的原因？
> 使用目前的OC引导也是一样，到了`OConsoleUsers: time(0) 0->0, lin 0, llk 1, IOConsoleUsers: gIOScreenLockState 3, hs 0, bs 0, nov 0, sm 0x0`之后就重启了

安装还是安装后替换EFI 出现？

**Comment by mxpazyj** [comment]
安装后替换EFI出现

**Comment by mxpazyj** [comment]
Fix by [更新最新驱动：whatevergreen、lilu](https://github.com/daliansky/XiaoXinPro-13-2019-hackintosh/commit/527f93f446a068c070009ecd3ab4663d0235a7bf)
