### ISSUE TITLE
i5 机型添加 1440 * 900 HiDPI 并修复闪屏/ Fixing 1440 * 900 HiDPI and above on i5 models and fixing screen flickering

### ISSUE THREAD

**Issue by sarkrui** [daliansky/XiaoXinPro-13-2019-hackintosh#5]
If you encounter the issue of not having the `1440 * 900` HiDPI or higher ones, you may try to change your `ig-platform-id` to `0x3EA5009`  (as the [OC-1.3 EFI](https://github.com/daliansky/XiaoXinPro-13-2019-hackintosh/releases/download/v1.3/EFI-OC0.54-PRO13.zip) comes with `0x3EA50004`). For editing details, please see the 1st snapshot. However, please note that the new id will cause to some extent partially flickers whenever the screen is frequently refreshed.
****
宪武最新的 OC-v1.3 版本使用了 `0x3EA50004` ig-platform-id, 该 id 在 `i5-10210u`机型上最高仅支持 1280 * 800 HiDPI，如果您觉得画面放大倍率偏大，可以根据图 1 截图手动更改注入 ID 为 `0x3EA0009` 经测试，该 ID 最高可支持 1650 * 1050 HiDPI，同时花屏概率也毕竟低（仍会出现）。
![kKI52fNEURsoBar](https://i.loli.net/2020/01/19/kKI52fNEURsoBar.png)
![RCisoBD8H639w7T](https://i.loli.net/2020/01/19/RCisoBD8H639w7T.png)

**Comment by M69W** [comment]
待测试，
我的机子是i7，需要更多不同机型测试
如你所说真是CPU或机型的缘故，下个版本将会区分或特别说明

PS：目前所有的EFI 初衷是想不区分i5和i7，尽量通用

**Comment by sarkrui** [comment]
i7 群里的朋友确实反馈没有该问题，i5 则有好几位提出了，补充一点 `0x3EA50004` 最高支持 16:9 的1440 * 810 HiDPI （不是 900），因此该分辨率下会出现屏幕上下有黑条的情况。

**Comment by M69W** [comment]
现阶段，i5安装和驱动集显不需要仿冒CPUID
但i7需要，不然卡+++++++

后来发现i5, i7可以使用仿冒同一个CPUID
为了通用EFI就统一使用仿冒同一个CPUID

目前i7需要开启DVMT不然开机会重启
但这个DVMT对i5“似乎”没影响

**Comment by sarkrui** [comment]
#### 2020/02/20 更新:
~~`0x3EA50004` 最高支持 16:9 的1440 * 810 HiDPI （不是 900）~~
之前使用`0x3EA50004` 或`0x3EA5009` 要么出现 HiDPI 最高分辨率只有 1280 * 800 或者盒盖唤醒后出现闪屏的问题。通过方法 [Windows10 下修正下列高级【隐藏】选项](https://github.com/daliansky/XiaoXinPro-13-2019-hackintosh/blob/master/EFI/EFI-OC-PRO13-AOAC/EFI-OC.md) 将 `DVMT Pre-Allocated` 容量从 32M 扩充至 64M，经测试，结合`0x3EA50004` ig-platform-id 可以**既保证完整的 HiDPI 分辨率选项，‘AOAC’ 唤醒后不闪屏！** 欢迎 i5 机友测试反馈

**Comment by kk1987** [comment]
@sarkrui 你好，可以分享修改DVMT的具体教程吗？链接里提到的“@PS@Donald 的教程——《修改DVMT Pre-Allocated数值方法》”不知道在哪里。。我从别处找的支持setup_var的EFI shell都没有办法在这个机器上运行。。

**Comment by M69W** [comment]
> @sarkrui 你好，可以分享修改DVMT的具体教程吗？链接里提到的“@ps@Donald 的教程——《修改DVMT Pre-Allocated数值方法》”不知道在哪里。。我从别处找的支持setup_var的EFI shell都没有办法在这个机器上运行。。

QQ群
自行改 BIOS 有风险，出任何问题自负

**Comment by sarkrui** [comment]
[小新PRO13修改DVMT说明.zip](https://github.com/daliansky/XiaoXinPro-13-2019-hackintosh/files/4249118/PRO13.DVMT.zip)
@kk1987  自行改 BIOS 有风险，出任何问题自负。

**Comment by kk1987** [comment]
感谢。不过我改了DVMT prealloc=64M之后还是闪屏。机器是i7，最新clone的EFI，试过Clover和OC、ig-platform-id=0x3EA50004和0x3EA50009，貌似都没有任何区别。HiDPI分辨率是用one-key-hidpi脚本手工添加的（原生似乎永远只有1280x800）

**Comment by sarkrui** [comment]
@kk1987 我自己用的不是 i7，所以没有测试过。你可以试着用 one-key-hidpi 手动注入更高的 HiDPI 分辨率，如 `1600x1000` ，`1440x900`；再者可以试试 clean nvram

**Comment by kk1987** [comment]
感谢，好像是Clover下面不太work，切换到OC、删除DVMT patching、注入0x3EA50004之后似乎不会闪屏了。

BTW 可以讲解一下README.md中提到的“仿真睡眠”具体是指什么吗？我的机器选择睡眠后除了屏幕和键盘灯熄灭，CPU似乎是在继续工作的（电源指示灯常亮，风扇不立即停转，机身微发热、每小时掉电5-10%），这样正常吗？

**Comment by sarkrui** [comment]
`仿真睡眠` = `AOAC`(Always On Always Connected)
i7 有独显，要确保用 `SSDT` 禁用了，我自己不是 i7 机型，了解不多

**Comment by M69W** [comment]
> `仿真睡眠` = `AOAC`(Always On Always Connected)
> i7 有独显，要确保用 `SSDT` 禁用了，我自己不是 i7 机型，了解不多

i5也有独显的机型

**Comment by sarkrui** [comment]
已解决，详情参考 [EFI 安装说明](https://github.com/daliansky/XiaoXinPro-13-2019-hackintosh/blob/master/EFI/EFI-OC-PRO13-AOAC/EFI-OC.md#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95)
