### ISSUE TITLE
耳机播放声音很奇怪，尤其是人声

### ISSUE THREAD

**Issue by skrbug** [daliansky/XiaoXinPro-13-2019-hackintosh#9]
外放没有问题，插上耳机后，声音有点小，并且有点嘈杂，有遇到这个问题的小伙伴吗？

**Comment by xgtian66** [comment]
我遇到了，只有环境声音，人声嘈杂，还没解决

**Comment by sarkrui** [comment]
OpenCore 引导，`PciRoot(0x0)/Pci(0x1f,0x3)` 下 注入 
```
device-id C89D0000 DATA
layout-id 0B000000 DATA
```
外放与耳机表现一切正常
_提 issue 的时候，请附上机型与使用的 EFI 版本_

**Comment by Hush-vv** [comment]
切换一下麦克风。解决。

**Comment by xgtian66** [comment]
更换clover以后，底噪没了。但是不能插耳机自动切换输出设备了，必须手动切换。不能自动切换体验真的不太好


来自 16s Pro

-------- 原始邮件 --------
发件人：Hush-vv <notifications@github.com>
时间：2020年3月31日 15:52
收件人：daliansky/XiaoXinPro-13-hackintosh <XiaoXinPro-13-hackintosh@noreply.github.com>
抄送：xgtian66 <tianwl16@lzu.edu.cn>,Comment <comment@noreply.github.com>
主题：Re: [daliansky/XiaoXinPro-13-hackintosh] 耳机播放声音很奇怪，尤其是人声 (#9)
